[package]
name = "concordium-rust-bindings"
version = "0.1.0"
authors = ["Concordium AG <developers@concordium.com>"]
edition = "2018"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[profile.dev]
opt-level = 3

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = { version = "0.2.80", features = ["serde-serialize"] }
pairing = "0.15"
anyhow = "1.0"
ed25519-dalek = {version = "=1.0.0", features = ["serde"] }
hex = "0.4"
sha2 = "0.9"
either = "1.6"
# Used by the tempoary schema_json.rs
num-bigint = "0.4.3"
num-traits = "0.2.15"

[dependencies.id]
path = "../../deps/concordium-base/rust-src/id"
version = "0"

[dependencies.curve_arithmetic]
path = "../../deps/concordium-base/rust-src/curve_arithmetic"
version = "0"

[dependencies.dodis_yampolskiy_prf]
path = "../../deps/concordium-base/rust-src/dodis_yampolskiy_prf"
version = "0"

[dependencies.crypto_common]
path = "../../deps/concordium-base/rust-src/crypto_common"
version = "0"

[dependencies.pedersen_scheme]
path = "../../deps/concordium-base/rust-src/pedersen_scheme"
version = "0"

[dependencies.ps_sig]
path = "../../deps/concordium-base/rust-src/ps_sig"
version = "0"

[dependencies.concordium-contracts-common]
features = ["derive-serde"]
path = "../../deps/concordium-base/concordium-contracts-common/concordium-contracts-common"
version = "3.1.0"

[dependencies.ed25519_hd_key_derivation]
path = "../../deps/concordium-base/rust-src/ed25519_hd_key_derivation"
version = "1.0.0"

[dependencies.key_derivation]
path = "../../deps/concordium-base/rust-src/key_derivation"
version = "1.0.0"

[lib]
name = "concordium_rust_bindings"
crate-type = ["cdylib"]
path = "src/lib.rs"
