[workspace]
members = ["packages/*"]

[workspace.package]
authors = ["Concordium AG <developers@concordium.com>"]
edition = "2021"

[profile.dev]
opt-level = 3

[workspace.dependencies]
anyhow = "1.0"
concordium_rust_bindings_common = { path = "./packages/common" }
either = "1.6"
hex = "0.4"
rand = { version = "=0.7", features = ["wasm-bindgen"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.5"
thiserror = "1.0"
wasm-bindgen = { version = "0.2.80", features = ["serde-serialize"] }

[workspace.dependencies.concordium_base]
path = "../../deps/concordium-base/rust-src/concordium_base"

[workspace.dependencies.ed25519_hd_key_derivation]
path = "../../deps/concordium-base/rust-src/ed25519_hd_key_derivation"

[workspace.dependencies.key_derivation]
path = "../../deps/concordium-base/rust-src/key_derivation"
