export const V0_PIGGYBANK_SCHEMA =
    'AQAAAAkAAABQaWdneUJhbmsBFQIAAAAGAAAASW50YWN0AgcAAABTbWFzaGVkAgAAAAAA';
export const CIS2_WCCD_STATE_SCHEMA =
    '//8CAQAAAA8AAABDSVMyLXdDQ0QtU3RhdGUAAQAAAAoAAABnZXRCYWxhbmNlAhQAAQAAAAUAAABvd25lchUCAAAABwAAAEFjY291bnQBAQAAAAsIAAAAQ29udHJhY3QBAQAAAAwbJQAAAA==';
export const CIS2_WCCD_STATE_GET_BALANCE_RETURN_VALUE_SCHEMA = 'GyUAAAA';
export const TEST_CONTRACT_SCHEMA =
    '//8CAQAAAAwAAABUZXN0Q29udHJhY3QBBAIDAQAAABAAAAByZWNlaXZlX2Z1bmN0aW9uBgYIBw==';
export const TEST_CONTRACT_RECEIVE_ERROR_SCHEMA = 'Bw';
export const TEST_CONTRACT_INIT_ERROR_SCHEMA = 'Aw';
export const AUCTION_WITH_ERRORS_VIEW_RETURN_VALUE_SCHEMA =
    'FAAEAAAADQAAAGF1Y3Rpb25fc3RhdGUVAgAAAAoAAABOb3RTb2xkWWV0AgQAAABTb2xkAQEAAAALDgAAAGhpZ2hlc3RfYmlkZGVyFQIAAAAEAAAATm9uZQIEAAAAU29tZQEBAAAACwQAAABpdGVtFgIDAAAAZW5kDQ';
