name: Deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  NODE_VERSION: 18.16.0
  RUST_VERSION: 1.62
  RUST_FMT: nightly-2023-04-01-x86_64-unknown-linux-gnu

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            packages/rust-bindings
            deps/concordium-deps

      - name: Get wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Get dependencies
        run: yarn install --immutable

      - name: Build release
        run: yarn build

      - name: Store build-release
        uses: actions/upload-artifact@v3
        with:
          name: build-release
          path: |
            packages/rust-bindings/pkg
            !packages/rust-bindings/pkg/**/.gitignore
            !packages/rust-bindings/pkg/**/README.md
            packages/rust-bindings/package.json
            packages/rust-bindings/README.md
            packages/common/lib
            packages/common/grpc
            packages/common/package.json
            packages/common/README.md
            packages/nodejs/lib
            packages/nodejs/grpc
            packages/nodejs/package.json
            packages/nodejs/README.md
            packages/web/lib
            packages/web/package.json
            packages/web/README.md

  build-typedoc:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Get build-output
        uses: actions/download-artifact@v3
        with:
          name: build-release

      - name: Get dependencies
        run: yarn install --immutable

      - name: Generate typedoc documentation
        run: yarn typedoc

      - name: Store typedoc
        uses: actions/upload-artifact@v3
        with:
          name: typedoc-build
          path: typedoc

  deploy-typedoc:
    needs: build-typedoc
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get typedoc
        uses: actions/download-artifact@v3
        with:
          name: typedoc-build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload GH pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './typedoc'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
